apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-amqp-test
  labels:
    app: rabbitmq-test
spec:
  containers:
    - name: rabbitmq-test
      image: rabbitmq-amqp-test:latest
      imagePullPolicy: Never
      env:
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_VHOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_VHOST
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: TEST_MESSAGE_TTL
          value: "5000"
        - name: TEST_MESSAGE_COUNT
          value: "5"
  restartPolicy: Never
