apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-test
  labels:
    app: debug
spec:
  containers:
    - name: rabbitmq-test
      image: alpine:latest
      command: ["/bin/sh", "-c", "apk add --no-cache curl && sleep 3600"]
      env:
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_VHOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_VHOST
