#!/bin/bash
echo "=== Verifying Structure ==="
echo ""
echo "1. GraphRAG location:"
[ -d "GraphRAG/src/domain" ] && echo "  ✅ GraphRAG/src/domain exists" || echo "  ❌ Missing"
echo ""
echo "2. Legacy services:"
[ -d "legacy_project/services/worker-service" ] && echo "  ✅ legacy_project/services/worker-service exists" || echo "  ❌ Missing"
echo ""
echo "3. New api-service:"
[ -d "api-service" ] && echo "  ✅ api-service exists" || echo "  ❌ Missing"
echo ""
echo "4. Auth-service:"
[ -d "legacy_project/services/auth-service" ] && echo "  ✅ auth-service in legacy_project" || echo "  ❌ Missing"
