apiVersion: batch/v1
kind: Job
metadata:
  name: queue-service-api-test
spec:
  template:
    spec:
      containers:
        - name: test
          image: python:3.9-slim
          command: ["/bin/sh", "/app/queue-service-api-test-init.sh"]
          env:
            - name: QUEUE_SERVICE_HOST
              value: "queue-service"
            - name: QUEUE_SERVICE_PORT
              value: "8080"
          volumeMounts:
            - name: test-script
              mountPath: /app
      volumes:
        - name: test-script
          configMap:
            name: queue-service-api-test-script
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 1
