apiVersion: v1
kind: Service
metadata:
  name: image-worker
  labels:
    app: image-worker
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: image-worker
