apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    app: test-job
    service: validate-queue
spec:
  template:
    metadata:
      labels:
        app: test-job
        service: validate-queue
    spec:
      containers:
        - name: test
          image: test-job:latest
          imagePullPolicy: Never
          env:
            - name: QUEUE_SERVICE_HOST
              value: queue-service-test
            - name: QUEUE_SERVICE_PORT
              value: "8080"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_VHOST
      restartPolicy: Never
