apiVersion: v1
kind: Pod
metadata:
  name: profile-api-test
spec:
  containers:
    - name: profile-api-test
      image: python:3.9-slim
      command: ["/bin/sh", "-c"]
      args:
        - |
          pip install requests
          python /tests/profile-api-test.py
      volumeMounts:
        - name: test-scripts
          mountPath: /tests
  volumes:
    - name: test-scripts
      configMap:
        name: profile-api-test-scripts
