apiVersion: v1
kind: Service
metadata:
  name: queue-service
  labels:
    app: queue-service
    tier: queue
spec:
  selector:
    app: queue-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
