apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-amqp-test
  labels:
    app: debug
spec:
  containers:
    - name: rabbitmq-amqp-test
      image: rabbitmq-amqp-test:latest
      imagePullPolicy: Never
      env:
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_VHOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_VHOST
