apiVersion: v1
kind: ConfigMap
metadata:
  name: api-service-config
data:
  API_POSTGRES_DSN: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
  API_REDIS_HOST: "redis"
  API_REDIS_PORT: "6379"
  API_RABBITMQ_PASSWORD: "guest"
  API_AUTH_URL: "http://auth-service:3000"

